export enum DocumentStatus {
  REQUESTING = 'REQUESTING',
  PENDING = 'PENDING',
  AVAILABLE = 'AVAILABLE',
  BORROWED = 'BORROWED',
  DELETED = 'DELETED'
}

export enum RequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELED = 'CANCELED',
  DONE = 'DONE',
  EXPIRED = 'EXPIRED'
}

export enum Role {
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}